# Generated by Django 4.2.4 on 2023-08-26 15:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('body', models.TextField()),
                ('created', models.DateTimeField(default=datetime.datetime(2023, 8, 26, 15, 1, 17, 300045))),
                ('update_time', models.DateTimeField(default=datetime.datetime(2023, 8, 26, 15, 1, 17, 300061))),
            ],
            options={
                'db_table': 'Todo',
            },
        ),
    ]
