# Generated by Django 4.2.4 on 2023-08-26 15:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 26, 15, 15, 24, 265956)),
        ),
        migrations.AlterField(
            model_name='todomodel',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 26, 15, 15, 24, 265970)),
        ),
    ]
